name: Install Nginx

on:
  workflow_dispatch:

jobs:
  install_nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Update apt Package and Install Ansible
        run: |
          sudo apt update
          sudo apt install ansible
          # python -m pip install --upgrade pip
          # pip install ansible

      - name: Set up SSH key
        run: |
          echo "$PRIVATE_SSH_KEY" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i inventory.ini install-nginx.yml
