name: Install Nginx

on:
  workflow_dispatch:

jobs:
  install_nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Update apt Package and Install Ansible
        run: |
          sudo apt update
          sudo apt install ansible
          # python -m pip install --upgrade pip
          # pip install ansible

      - name: Run Playbook
        with:
          playbook: nginx-install.yml
          directory: ./
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          inventory: |
            [node1]
            manage-node ansible_host=65.1.1.18 ansible_user=ubuntu ansible_ssh_private_key_file=/home/runner/.ssh/id_rsa
          options: |
            --inventory.ini

      # - name: Set up Private SSH key
      #   run: |
      #     mkdir -p /home/runner/.ssh
      #     echo "${{ secrets.PRIVATE_SSH_KEY }}" > /home/runner/.ssh/id_rsa
      #     chmod 400 /home/runner/.ssh/id_rsa

      # - name: Ping Node
      #   run: |
      #     ansible -i "3.110.187.195" -u ubuntu --private-key=/home/runner/.ssh/id_rsa -m ping

      # - name: Run Ansible playbook
      #   run: |
      #     ansible-playbook -i inventory.ini nginx-install.yml
